### ISSUE TITLE
Неточно парсит команды

### ISSUE THREAD

**Issue by wireje** [GoBJIuH/NullBot#1]
я на гитхабе недавно, не знаю, как правильно оформлять issues с коммитами. так что извиняюсь заранее.

итак, к теме.
проблема в том, что если имеется две команды, например, func и func2, то вызываться всегда будет первая, т.к. у тебя используется "startsWith". я решил это исправить. только теперь команды **в коде** нужно писать точно. т.е. вместо "ты любишь меня" _(в модуле conversations.js)_  - "ты любишь меня?".

вот как я исправил проблему.

в файле **moduleloader.js** внес следующие изменения:
вместо `if(format(message.content).startsWith(
					(prefix ? prefix : '') + name))`
написал `				let goodname = (prefix ? prefix : '') + escapeRegex(name);
				var regex = new RegExp("^\\"+ goodname + "(\\s|$)");
				if(format(message.content).match(regex))`

также добавил функцию **escapeRegex**:
`function escapeRegex(value) {
    return value.replace( /[\-\[\]{}()*+?.,\\\^$|#\s]/g, "\\$&" );
}`

**Comment by Capster** [comment]
Форкаешь этот репозиторий, вносишь в своем форке необходимые изменения и потом создаешь [Pull Request](https://github.com/GoBJIuH/NullBot/compare), в котором указываешь для слияния свой форк и основную ветку этого репозитория (**master**)

**Comment by GoBJIuH** [comment]
Проблема понятна, но твой код я что-то вообще понять не могу. Можешь объяснить?

**Comment by wireje** [comment]
https://regex101.com/r/oI5rQ9/1
вот смотри. вместо **+func2** в регулярном выражении можешь подставить любую команду. он подсветит найденное.

если подробно, то т.к. я использовал регулярные выражения - в команде не должно быть служебных символов для regexp, поэтому мы экранируем эти символы функцией escapeRegex.
а дальше вроде все понятно. выше ссылка на проверку регулярного выражения

**Comment by GoBJIuH** [comment]
Я понимаю что писать "ты любишь меняабгд1" не очень красиво, но это было сделано дабы можно было ставить вопросительные знаки/не ставить их, ставить пробелы и так далее.
Твой код не будет работать так, как мне хотелось бы, хоть и исправляет проблему. Я предлагаю сделать так: на входе тупо удалить все знаки препинания [?.,итд] и заодно заменить **\s** на обычные пробелы, после чего простым "===" сравнивать с командой. Устраивает?

**Comment by wireje** [comment]
хм, если сравнивать с помощью "===", то аргументы не будут парситься. т.е. **+help uptime** уже не сработает, как и другие сложные команды. может, просто сплит сделать? надо подумать

**Comment by GoBJIuH** [comment]
Поправил. Спасибо за решение :)
